hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        driverclassname: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/employee_directory
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true